### ISSUE TITLE
Feature: Add All Received Transactions To Accounts

### ISSUE THREAD

**Issue by tboeckmann** [polkascan/polkascan-pre#10]
In Polkascan, I can see transactions consisting of balance transfers and extrinsics initiated by an account (OUT), but I cannot see _all_ the received transactions (IN).

For example, this [account page](https://polkascan.io/pre/edgeware-testnet/account/5EU2BwdEH8rojoKuJ16p3t1Gs8uUUp6SoaomKud2FmXBvdbp) shows contract calls deliberately sent to an account address:

![image](https://user-images.githubusercontent.com/2022378/69884027-e3a89900-12d6-11ea-900b-cfef5e6651ad.png)

But when looking at the [recipient account](https://polkascan.io/pre/edgeware-testnet/account/5EFasuRNh76upGNiPRZfFbfmmWJdbjXEd5TZpw9k1aNzHCdt), the transactions are not shown:
![image](https://user-images.githubusercontent.com/2022378/69884077-13f03780-12d7-11ea-9daf-119d48be49b5.png)

- Do you plan to extend Polkascan to support this?
- If not, are you accepting pull requests and what would be you advice on approach for implementing it?

**Comment by emielvanderhoek** [comment]
The testnet has reset so the hyperlinks you provided are no longer valid. That said: incoming transfers are now included on the transfer tab on the account details page.

Example: https://polkascan.io/pre/edgeware-testnet/account/5En4obYBUS2CoB8HskBT7tuXfRHz8BFYTWdijMN4XDxdiYBs#transfers

![afbeelding](https://user-images.githubusercontent.com/14069142/71356064-5da00b00-2581-11ea-9fe7-856f46bd4b1c.png)

**Comment by tboeckmann** [comment]
Hi @emielvanderhoek - that's great that the incoming transfers are now visible.

What about other types of incoming extrinsics, e.g. Contracts calls.

# Contracts call examples:

    Bob = `5Dd3GjWjB71xiJP6ZNJa5C14B83CHJzZt3FY6JjXzaabdWQ8`
    Alice = `5EU2BwdEH8rojoKuJ16p3t1Gs8uUUp6SoaomKud2FmXBvdbp`

## 1 Zero Value Transaction

In tx `0xcd46e6ae7086953ba0e58d447c85be78c46029f590d1c451c269e3b31d6ac5ba`, Bob  sent Alice an encrypted message as part of a zero value transaction. Bob used the data field in the Contracts call.

This can be seen here:
https://polkascan.io/pre/edgeware-testnet/transaction/0xcd46e6ae7086953ba0e58d447c85be78c46029f590d1c451c269e3b31d6ac5ba

![image](https://user-images.githubusercontent.com/2022378/71645312-54741400-2cce-11ea-8034-62971710cf9f.png)

## 2 Sending Value Transaction

In tx `0x8a4105e3d311b9122d52d017238e3a3518e371e3c5781bf9535578e24918a9eb`, Bob  sent Alice a payment of 0.02testEDG. Bob used the data field in the Contracts call to include an encrypted message.

This can be seen here:
https://polkascan.io/pre/edgeware-testnet/transaction/0x8a4105e3d311b9122d52d017238e3a3518e371e3c5781bf9535578e24918a9eb

![image](https://user-images.githubusercontent.com/2022378/71645295-242c7580-2cce-11ea-9253-1442bbcf936f.png)

---

Unfortunately, [Alice's account on Polkascan](https://polkascan.io/pre/edgeware-testnet/account/5EU2BwdEH8rojoKuJ16p3t1Gs8uUUp6SoaomKud2FmXBvdbp) does not show either of these tx.

![image](https://user-images.githubusercontent.com/2022378/71645307-432b0780-2cce-11ea-8762-a05bca657d08.png)

**Comment by robdefeo** [comment]
Hi @emielvanderhoek can this be re-opened base on @tboeckmann suggestion. Thanks

**Comment by tboeckmann** [comment]
Hi @emielvanderhoek - please could you re-open this issue? It does not appear to have been fixed.
