### ISSUE TITLE
homepage explorer & open source are difference

### ISSUE THREAD

**Issue by haoming06** [polkascan/polkascan-pre#11]
There are some difference between homepage and github, such as analytics,last 25 balance transfer ...
will you merge the official website source with open source?

**Comment by emielvanderhoek** [comment]
Hi the section you mention will probably not be available in the open-source repositories soon.
In general all work we do with public funding will find its way in open-source repositories. This includes all basic data entities, such as: blocks, extrinsics, events, runtimes, accounts and the way these building blocks are harvested.

We use our open-source components to build our platform polkascan.io. The components you mention in particular were not part of our public funding. These components are experimental and may change at any time. Additionally those components do not yet meet the criteria we set for our open-source stack. We require the components in our open-source stack to be general purpose en dbms agnostic, and these components do not meet those criteria. We try very hard to find a balance to build a reliable, general purpose block explorer platform that works on any type of hardware on one hand and to provide a valuable service to the community with our polkascan.io platform on the other hand.

I hope this helps!
