### ISSUE TITLE
Add in/out tag to balance transfers

### ISSUE THREAD

**Issue by joepetrowski** [polkascan/polkascan-pre#12]
In the "Balance Transfers" section of an account, you could make it more clear which direction funds are going by:

1. Adding a tag for "in" or "out"
2. Some stylistic difference (e.g. only making the other account a hyperlink)

For example:
![image](https://user-images.githubusercontent.com/25483142/71349191-ac907500-256e-11ea-8d32-07adcd1462e9.png)

Could have something more like Etherscan (where `0x7e1...` is the account being viewed):
![image](https://user-images.githubusercontent.com/25483142/71349204-b9ad6400-256e-11ea-8292-4dbd8b096b68.png)

**Comment by arjanz** [comment]
Added incoming/outgoing icon and removed hyperlinks to current account:

<img width="895" alt="Screenshot 2019-12-23 at 11 05 13" src="https://user-images.githubusercontent.com/5286904/71354468-56c2c980-257c-11ea-88c6-d65834247c9f.png">

**Comment by joepetrowski** [comment]
So fast, looks awesome! :raised_hands:
