### ISSUE TITLE
Display timestamp on transaction page

### ISSUE THREAD

**Issue by joepetrowski** [polkascan/polkascan-pre#3]
Right now, when you look at a transaction, you cannot see the date and time that transaction was made. To do that, you have to look at the block itself.

You should add a field to show the date and time of the block in the transaction info page.

![image](https://user-images.githubusercontent.com/25483142/67631846-13115380-f89c-11e9-9352-910a28a726d2.png)

![image](https://user-images.githubusercontent.com/25483142/67631853-2b816e00-f89c-11e9-858f-62d2eb699f6b.png)

**Comment by arjanz** [comment]
Added on transaction details, will be available in next release
