### ISSUE TITLE
Harvester-worker complains with latest Substrate: ValueError Index 8

### ISSUE THREAD

**Issue by phil-h-dlt** [polkascan/polkascan-pre#4]
Running polkascan's docker-compose, but replacing substrate node with a local latest Substrate docker image (running dev chain), I get the below exception in harvester-worker.

Version details:
Polkascan: 8dc0341
Substrate: c4e78a3, using Substrate's (master) docker image

harvester-worker_1   | [2019-10-28 09:26:43,829: ERROR/ForkPoolWorker-3] Task app.tasks.accumulate_block_recursive[75a0a78a-7ef8-4ffa-b00f-a6b4b8bd99c1] raised unexpected: HarvesterCouldNotAddBlock('0x3b758164fafb688c0ea60ec67efb31eaaf22090931eea4a7f90e7069f7e2008d',)
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/scalecodec/types.py", line 590, in process
harvester-worker_1   |     return self.value_list[self.index]
harvester-worker_1   | IndexError: list index out of range
harvester-worker_1   | 
harvester-worker_1   | During handling of the above exception, another exception occurred:
harvester-worker_1   | 
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 106, in accumulate_block_recursive
harvester-worker_1   |     block = harvester.add_block(block_hash)
harvester-worker_1   |   File "/usr/src/app/app/processors/converters.py", line 502, in add_block
harvester-worker_1   |     self.process_metadata(json_runtime_version, block_hash)
harvester-worker_1   |   File "/usr/src/app/app/processors/converters.py", line 205, in process_metadata
harvester-worker_1   |     metadata_decoder = substrate.get_block_metadata(block_hash)
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/substrateinterface/__init__.py", line 131, in get_block_metadata
harvester-worker_1   |     metadata_decoder.decode()
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/scalecodec/metadata.py", line 42, in process
harvester-worker_1   |     "MetadataV7Decoder",
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/scalecodec/base.py", line 248, in process_type
harvester-worker_1   |     obj.decode(check_remaining=False)
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/scalecodec/base.py", line 185, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/scalecodec/types.py", line 592, in process
harvester-worker_1   |     raise ValueError("Index '{}' not present in Enum value list".format(self.index))
harvester-worker_1   | ValueError: Index '8' not present in Enum value list
harvester-worker_1   | 
harvester-worker_1   | The above exception was the direct cause of the following exception:
harvester-worker_1   | 
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
harvester-worker_1   |     R = retval = fun(*args, **kwargs)
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 66, in __call__
harvester-worker_1   |     return super().__call__(*args, **kwargs)
harvester-worker_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
harvester-worker_1   |     return self.run(*args, **kwargs)
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 133, in accumulate_block_recursive
harvester-worker_1   |     raise HarvesterCouldNotAddBlock(block_hash) from exc
harvester-worker_1   | app.processors.converters.HarvesterCouldNotAddBlock: 0x3b758164fafb688c0ea60ec67efb31eaaf22090931eea4a7f90e7069f7e2008d
harvester-worker_1   | [2019-10-28 09:26:43,838: INFO/ForkPoolWorker-4] Task app.tasks.start_sequencer[6782d2f9-a544-478a-907f-f77753d

**Comment by arjanz** [comment]
Have you tried to to rebuild the docker images with docker-compose build --no-cache? I suspect it's because a dependency updated since last time you ran Polkascan (most likely the Scale codec for new Substrate metadata version) and the docker layer is still pulled from cache. 

In the future we will pin version numbers in our dependencies so this will be done automatically..
