### ISSUE TITLE
A question about  call rpc interface and return a error UnknownBlock

### ISSUE THREAD

**Issue by haoming06** [polkascan/polkascan-pre#6]
Hi,when I use polkascan sync substrate2.0 data,if the block num less than current reduct 256 then rpc interface can throw a error like this
`{
    "jsonrpc": "2.0",
    "error": {
        "code": -32603,
        "message": "Unknown error occured",
        "data": "Client(UnknownBlock(\"Unknown state for block Hash(0x29e5058aca17d31acc8c87bbb3836fe53bcbd66a9fc1b973df0a01c23f865f05)\"))"
    },
    "id": 3
}`
And the node start in Host OS
I sync substrate 1.0  data use  polkascan success, it can find the genesis block. But substrate2.0 error.
For example, If the block number has created 1000, can the program sync data from 1 block? What can do for  modify the node and polkascan config.
Need the polkascan start  with node together ?  And differ less than 256 blocks.
Thanks

**Comment by emielvanderhoek** [comment]
The block cannot be found on your node.
Either you are looking up a block by hash on the wrong network, or more likely you are not running an archive node and the block has already been pruned from the state.

Use the startup option `--pruning=archive`
