### ISSUE TITLE
Indexing modules data that currently goes to various params json columns

### ISSUE THREAD

**Issue by ksinghf** [polkascan/polkascan-pre#8]
We at Joystream have started work on a project that uses polkascan to harvest the Joystream blockchain data into a relational database using the polkascan harvester.

But there's a couple of issues in the way we want to store and index the data, and thought it might be best to discuss them with you.

For extrinsics specific to our SRML, the associated data ends up in the `params` column in the `data_extrinsic` table. However, we want to index the data in this column. The situation with `params` column appears also in other tables, for example the `data_democracy_proposal` table has a `params` json column as well.

We are debating if we should make a change in polkascan where the various `params` columns are instead moved to separate tables with columns indexed for querying purposes and linked to their current table via a fk relationship.

This will mean that for each module we develop, we will have a separate table in the polkascan database as well. Say for the Joystream forums module, we will create a `data_forum` table with the required columns that can then be indexed. Similarly, for the `data_democracy_proposal` table, the json column will be a separate table with indexed columns, and so on.

There is the clear con of maintaining these table schemas as we continue our development.

Do you have any plans to support such a use case, where the modules from different runtimes are mapped to different tables in harvester db?

Is there another approach you had in mind or would recommend we take?  I read through your development updates on medium and couldn't find a suggestion I could pursue.

**Comment by emielvanderhoek** [comment]
Hi @ksinghf ,

We intend to keep Polkascan as general purpose as possible. I.e. with everything we develop we try to find general purpose mechanisms that would work for any Substrate implementation. This is one of the reasons why we choose for the `json`-columns. No matter how many `params` and `extrinsic` has and no matter how many `attributes` an `event` has the model is general purpose. Obviously the `democracy`-tables deviate from this, but the urgency of having that for Kusama and Polkadot warranted exceptions.

We are working on a generalized indexing solution that would work for any Substrate module. However, it is unlikely that this will move into the open-source repositories anytime soon, for various reasons: 1) it is not ready and will take time to mature, 2) we may need to be opinionated about the dbms, 3) it may have a significant performance footprint. It is therefor at this point unknown if and when such feature would end up in the open-source repository.

If you would like to pursue development activity in a downstream fork isuggest the following considerations:
1. Most likely all the data you need is already in the `events`-table (if you properly design your events). You may want to consider simple ETL process to feed tailored tables with indexes that meet your expectations.
2. If you don't mind being opinionated about your dmbs, you may want to consider `Secondary Indexes and Generated Columns`. You can use that to place indexes on (parts of) `json`-data: https://dev.mysql.com/doc/refman/5.7/en/create-table-secondary-indexes.html
3. Also if you don't mind being opinionated about your dmbs, you may want to consider `Stored Procedures`. These procedures could contain the 'simple' ETL-process mentioned in (2) and thus limits the changes to you Polkascan-repo to a minimum of calling this stored procedure.
4. I'd recommend against using FK-definitions anywhere in a block explorer DB. Such databases can grow very large and FK have more cons than pros in this context. An index should suffice.

I hope this helps.

**Comment by ksinghf** [comment]
Thanks @emielvanderhoek. We have decided to try out the first approach you suggested.
